// Generated by CoffeeScript 1.4.0
(function() {

  $(document).ready(function() {
    $('#submit').click(function() {
      var Retypeemail, address, address_regex, birth, birth_regex, email, email_regex, firstname, isChecked, isChecked1, lastname, name_regex, phone, phone_regex, state;
      firstname = $('#firstname').val();
      lastname = $('#lastname').val();
      email = $('#email').val();
      Retypeemail = $('#Retypeemail').val();
      phone = $('#phone').val();
      state = $('#state').val();
      isChecked = $('input[name=radio1]:checked').val();
      birth = $('#birth').val();
      address = $('#address').val();
      isChecked1 = $('input[name=checkbox]:checked').val();
      name_regex = /^[a-zA-Z]{2,25}$/;
      email_regex = /^[\w\-\.\+]+\@[a-zA-Z0-9\.\-]+\.[a-zA-Z0-9]{2,4}$/;
      phone_regex = /^\(?([0-9]{3})\)?([0-9]{3})?([0-9]{4})$/;
      birth_regex = /^([0-9]{2})\/([0-9]{2})\/([0-9]{4})$/;
      address_regex = /^([a-zA-Z0-9_\.\-\/\:\;])+$/;
      if (!firstname.match(name_regex) || firstname.length === 0) {
        $('#errormessage1').text('* Please enter your First Name *');
        $('#firstname').css('box-shadow', '0px 0px 6px 1px #ff3333');
        $('#firstname').focus();
        $('#wrongfirst').show();
        $('#rightfirst').hide();
        return false;
      } else if (!lastname.match(name_regex) || lastname.length === 0) {
        $('#errormessage2').text('*Please enter your Last Name*');
        $('#lastname').css('box-shadow', '0px 0px 6px 1px #ff3333');
        $('#lastname').focus();
        $('#wronglast').show();
        $('#rightlast').hide();
        return false;
      } else if (!email.match(email_regex) || email.length === 0) {
        $('#errormessage3').text('* Please enter a email address *');
        $('#email').css('box-shadow', '0px 0px 6px 1px #ff3333');
        $('#email').focus();
        $('#wrongemail').show();
        $('#rightemail').hide();
        return false;
      } else if (Retypeemail !== email || Retypeemail.length === 0) {
        $('#errormessage4').text('* Please enter a Retype email address *');
        $('#Retypeemail').css('box-shadow', '0px 0px 6px 1px #ff3333');
        $('#Retypeemail').focus();
        $('#wrongRetypeemail').show();
        $('#rightRetypeemail').hide();
        return false;
      } else if (!phone.match(phone_regex) || phone.length === 0) {
        $('#errormessage5').text('* Please enter your Phone Number *');
        $('#phone').css('box-shadow', '0px 0px 6px 1px #ff3333');
        $('#phone').focus();
        $('#wrongphone').show();
        $('#rightphone').hide();
        return false;
      } else if (state === 'Please Choose your state') {
        $('#errormessage6').text('* Please Choose your state');
        $('#state').css('box-shadow', '0px 0px 6px 1px #ff3333');
        $('#state').focus();
        $('#wrongstate').show();
        $('#rightstate').hide();
        return false;
      } else if (!isChecked) {
        $('#errormessage7').text('* Please Choose any one option');
        return false;
      } else if (!birth.match(birth_regex) || birth.length === 0) {
        $('#errormessage8').text('* Please enter your Birth date *');
        $('#birth').css('box-shadow', '0px 0px 6px 1px #ff3333');
        $('#birth').focus();
        $('#wrongbirth').show();
        $('#rightbirth').hide();
        return false;
      } else if (!address.match(address_regex) || address.length === 0) {
        $('#errormessage9').text('* Please enter your Birth date *');
        $('#address').css('box-shadow', '0px 0px 6px 1px #ff3333');
        $('#address').focus();
        $('#wrongaddress').show();
        $('#rightaddress').hide();
        return false;
      } else if (!isChecked1) {
        $('#errormessage10').text('<---Please accept TERMS AND CONDITONS');
        return false;
      } else {
        alert('Form Submitted successfuly..!!! ');
        return true;
      }
    });
  });

  $(document).ready(function() {
    $('#firstname').click(function() {
      var firstname, name_regex;
      firstname = $('#firstname').val();
      name_regex = /^[a-zA-Z]{2,25}$/;
      if (!firstname.match(name_regex) || firstname === '' || firstname.length === 0) {
        $('#errormessage1').hide();
        $('#firstname').css({
          'background-color': '#ffffff',
          'box-shadow': 'none',
          'border': '1px solid #00a2de'
        });
        $('#rightfirst').hide();
        $('#wrongfirst').hide();
      } else {
        return false;
      }
    });
  });

  $(document).ready(function() {
    $('#firstname').blur(function() {
      var firstname, name_regex;
      firstname = $('#firstname').val();
      name_regex = /^[a-zA-Z]{2,25}$/;
      if (!firstname.match(name_regex) || firstname === '' || firstname.length === 0) {
        $('#errormessage1').show();
        $('#errormessage1').text('* Please enter a valid Name *');
        $('#firstname').focus();
        $('#firstname').css('box-shadow', '0px 0px 6px 1px #ff3333');
        $('#wrongfirst').show();
        $('#rightfirst').hide();
      } else {
        $('#errormessage1').hide();
        $('#firstname').addClass('success');
        $('#rightfirst').show();
        $('#wrongfirst').hide();
        return false;
      }
    });
  });

  $(document).ready(function() {
    $('#lastname').click(function() {
      var lastname, name_regex;
      lastname = $('#lastname').val();
      name_regex = /^[a-zA-Z]{2,15}$/;
      if (!lastname.match(name_regex) || lastname.length === 0) {
        $('#errormessage2').hide();
        $('#lastname').css({
          'background-color': '#ffffff',
          'box-shadow': 'none',
          'border': '1px solid #00a2de'
        });
        $('#rightlast').hide();
        $('#wronglast').hide();
      } else {
        return false;
      }
    });
  });

  $(document).ready(function() {
    $('#lastname').blur(function() {
      var lastname, name_regex;
      lastname = $('#lastname').val();
      name_regex = /^[a-zA-Z]{2,15}$/;
      if (!lastname.match(name_regex) || lastname.length === 0) {
        $('#errormessage2').show();
        $('#errormessage2').text('* Please enter a valid Name *');
        $('#lastname').focus();
        $('#lastname').css('box-shadow', '0px 0px 6px 1px #ff3333');
        $('#wronglast').show();
        $('#rightlast').hide();
      } else {
        $('#errormessage2').hide();
        $('#lastname').addClass('success');
        $('#rightlast').show();
        $('#wronglast').hide();
        return false;
      }
    });
  });

  $(document).ready(function() {
    $('#email').click(function() {
      var email, email_regex;
      email = $('#email').val();
      email_regex = /^[\w\-\.\+]+\@[a-zA-Z0-9\.\-]+\.[a-zA-Z0-9]{2,4}$/;
      if (!email.match(email_regex) || email.length === 0) {
        $('#errormessage3').hide();
        $('#email').css({
          'background-color': '#ffffff',
          'box-shadow': 'none',
          'border': '1px solid #00a2de'
        });
        $('#rightemail').hide();
        $('#wrongemail').hide();
      } else {
        return false;
      }
    });
  });

  $(document).ready(function() {
    $('#email').blur(function() {
      var email, email_regex;
      email = $('#email').val();
      email_regex = /^[\w\-\.\+]+\@[a-zA-Z0-9\.\-]+\.[a-zA-Z0-9]{2,4}$/;
      if (!email.match(email_regex) || email.length === 0) {
        $('#errormessage3').show();
        $('#errormessage3').text('* Please enter a valid email *');
        $('#email').focus();
        $('#email').css('box-shadow', '0px 0px 6px 1px #ff3333');
        $('#wrongemail').show();
        $('#rightemail').hide();
      } else {
        $('#errormessage3').hide();
        $('#email').addClass('success');
        $('#rightemail').show();
        $('#wrongemail').hide();
        return false;
      }
    });
  });

  $(document).ready(function() {
    $('#Retypeemail').click(function() {
      var Retypeemail, email, email_regex;
      Retypeemail = $('#Retypeemail').val();
      email = $('#email').val();
      email_regex = /^[\w\-\.\+]+\@[a-zA-Z0-9\.\-]+\.[a-zA-Z0-9]{2,4}$/;
      if (Retypeemail !== email || Retypeemail.length === 0) {
        $('#errormessage4').hide();
        $('#Retypeemail').css({
          'background-color': '#ffffff',
          'box-shadow': 'none',
          'border': '1px solid #00a2de'
        });
        $('#rightRetypeemail').hide();
        $('#wrongRetypeemail').hide();
      } else {
        return false;
      }
    });
  });

  $(document).ready(function() {
    $('#Retypeemail').blur(function() {
      var Retypeemail, email, email_regex;
      Retypeemail = $('#Retypeemail').val();
      email = $('#email').val();
      email_regex = /^[\w\-\.\+]+\@[a-zA-Z0-9\.\-]+\.[a-zA-Z0-9]{2,4}$/;
      if (Retypeemail !== email || Retypeemail.length === 0) {
        $('#errormessage4').show();
        $('#errormessage4').text('* Please enter email as you entered above *');
        $('#Retypeemail').focus();
        $('#Retypeemail').css('box-shadow', '0px 0px 6px 1px #ff3333');
        $('#wrongRetypeemail').show();
        $('#rightRetypeemail').hide();
      } else {
        $('#errormessage4').hide();
        $('#Retypeemail').addClass('success');
        $('#rightRetypeemail').show();
        $('#wrongRetypeemail').hide();
        return false;
      }
    });
  });

  $(document).ready(function() {
    $('#phone').click(function() {
      var phone, phone_regex;
      phone = $('#phone').val();
      phone_regex = /^\(?([0-9]{3})\)?([0-9]{3})?([0-9]{4})$/;
      if (!phone.match(phone_regex) || phone.length === 0) {
        $('#errormessage5').hide();
        $('#phone').css({
          'background-color': '#ffffff',
          'box-shadow': 'none',
          'border': '1px solid #00a2de'
        });
        $('#rightphone').hide();
        $('#wrongphone').hide();
      } else {
        return false;
      }
    });
  });

  $(document).ready(function() {
    $('#phone').blur(function() {
      var phone, phone_regex;
      phone = $('#phone').val();
      phone_regex = /^\(?([0-9]{3})\)?([0-9]{3})?([0-9]{4})$/;
      if (!phone.match(phone_regex) || phone.length === 0) {
        $('#errormessage5').show();
        $('#errormessage5').text('* Please enter your 10 digits Mobile Number *');
        $('#phone').focus();
        $('#phone').css('box-shadow', '0px 0px 6px 1px #ff3333');
        $('#wrongphone').show();
        $('#rightphone').hide();
      } else {
        $('#errormessage5').hide();
        $('#phone').addClass('success');
        $('#rightphone').show();
        $('#wrongphone').hide();
        return false;
      }
    });
  });

  $(document).ready(function() {
    $('#state').click(function() {
      var state;
      state = $('#state').val();
      if (state === 'Please Choose your state') {
        $('#errormessage6').hide();
        $('#state').css({
          'background-color': '#ffffff',
          'box-shadow': 'none',
          'border': '1px solid #00a2de'
        });
        $('#rightstate').hide();
        $('#wrongstate').hide();
      } else {
        return false;
      }
    });
  });

  $(document).ready(function() {
    $('#state').blur(function() {
      var state;
      state = $('#state').val();
      if (state === 'Please Choose your state') {
        $('#errormessage6').show();
        $('#errormessage6').text('* Please select any state *');
        $('#state').focus();
        $('#state').css('box-shadow', '0px 0px 6px 1px #ff3333');
        $('#wrongstate').show();
        $('#rightstate').hide();
      } else {
        $('#errormessage6').hide();
        $('#state').addClass('success');
        $('#rightstate').show();
        $('#wrongstate').hide();
        return false;
      }
    });
  });

  $(document).ready(function() {
    $('.radio').click(function() {
      var isChecked;
      isChecked = $('input[name=radio1]:checked').val();
      if (isChecked) {
        $('#errormessage7').hide();
      } else {
        return false;
      }
    });
  });

  $(document).ready(function() {
    $('#birth').click(function() {
      var birth, birth_regex;
      birth = $('#birth').val();
      birth_regex = /^([0-9]{2})\/([0-9]{2})\/([0-9]{4})$/;
      if (!birth.match(birth_regex) || birth.length === 0) {
        $('#errormessage8').hide();
        $('#birth').css({
          'background-color': '#ffffff',
          'box-shadow': 'none',
          'border': '1px solid #00a2de'
        });
        $('#rightbirth').hide();
        $('#wrongbirth').hide();
      } else {
        return false;
      }
    });
  });

  $(document).ready(function() {
    $('#birth').blur(function() {
      var birth, birth_regex;
      birth = $('#birth').val();
      birth_regex = /^([0-9]{2})\/([0-9]{2})\/([0-9]{4})$/;
      if (!birth.match(birth_regex) || birth.length === 0) {
        $('#errormessage8').show();
        $('#errormessage8').text('* Please enter a valid Date of birth *');
        $('#birth').focus();
        $('#birth').css('box-shadow', '0px 0px 6px 1px #ff3333');
        $('#wrongbirth').show();
        $('#rightbirth').hide();
      } else {
        $('#errormessage8').hide();
        $('#birth').addClass('success');
        $('#rightbirth').show();
        $('#wrongbirth').hide();
        return false;
      }
    });
  });

  $(document).ready(function() {
    $('#address').click(function() {
      var address, address_regex;
      address = $('#address').val();
      address_regex = /^([a-zA-Z0-9_\.\-\/])+$/;
      if (!address.match(address_regex) || address.length === 0) {
        $('#errormessage9').hide();
        $('#address').css({
          'background-color': '#ffffff',
          'box-shadow': 'none',
          'border': '1px solid #00a2de'
        });
        $('#rightaddress').hide();
        $('#wrongaddress').hide();
      } else {
        return false;
      }
    });
  });

  $(document).ready(function() {
    $('#address').blur(function() {
      var address, address_regex;
      address = $('#address').val();
      address_regex = /^([a-zA-Z0-9_\.\-\/\:\;])+$/;
      if (!address.match(address_regex) || address.length === 0) {
        $('#errormessage9').show();
        $('#errormessage9').text('* Please enter your valid address *');
        $('#address').focus();
        $('#address').css('box-shadow', '0px 0px 6px 1px #ff3333');
        $('#wrongaddress').show();
        $('#rightaddress').hide();
      } else {
        $('#errormessage9').hide();
        $('#address').addClass('success');
        $('#rightaddress').show();
        $('#wrongaddress').hide();
        return false;
      }
    });
  });

  $(document).ready(function() {
    $('#checkbox').click(function() {
      var isChecked;
      isChecked = $('input[name=checkbox]:checked').val();
      if (isChecked) {
        $('#errormessage10').hide();
      } else {
        return false;
      }
    });
  });

}).call(this);
